// § 36 (2026-09-25): every outbound WhatsApp message on record, and the
// template's full text — the Odoo side.
//
//   1. x_whatsapp_template.x_body_text «نص القالب المعتمد» (text header, body,
//      footer — one per line, {{n}} unfilled) and x_buttons_text «تسميات
//      الأزرار» (one per line). The template sync fills them.
//   2. x_wa_message.x_echo_status «صدى المناقشة» (posted / pending / failed /
//      none), x_echo_message_id «رسالة المناقشة» (the Discuss message that
//      shows the send), x_backfilled «مستكمل».
//   3. server action «UTAK — سطر حالة رسالة واتساب» on x_wa_message (code,
//      Settings group): run as a row, it edits the status line of the Discuss
//      message the row points to — generated by src/wa-record.ts
//      heldLineActionCode(), and checked here in python3 against the TS.
//   4. the list and the form of x_wa_message show the two new states
//      (inherited views; the base views are untouched).
//
//   node --experimental-strip-types --experimental-loader=./tests/loader.mjs scripts/s36-20260925-odoo.mts             dry-run: the plan
//   … --apply                 snapshot first, then write (idempotent)
//   … --verify                read-only checks (and the python3 check)
//   … --rollback [--apply]    views off, the action a no-op (nothing deleted)
//   … --rollback --drop [--apply]   and delete what this script created — not without a decision
//
// Rollback file: scripts/artifacts/s36-20260925-odoo-rollback.json. No WhatsApp.
// Tenant shared with prod.
import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { execFileSync } from "node:child_process";
import { call } from "./lib/odoo-cli.mjs";
import { HELD_LINE_ACTION_NAME, STATUS_MARKERS, heldLineActionCode, replaceStatusLine, statusLineFor } from "../src/wa-record.ts";

const APPLY = process.argv.includes("--apply");
const VERIFY = process.argv.includes("--verify");
const ROLLBACK = process.argv.includes("--rollback");
const DROP = process.argv.includes("--drop");
const RB = new URL("./artifacts/s36-20260925-odoo-rollback.json", import.meta.url).pathname;
const log = (...a: unknown[]) => console.log(...a);

const TEMPLATE_FIELDS = [
  { name: "x_body_text", ttype: "text", field_description: "نص القالب المعتمد", help: "نص القالب كما يقرؤه المستلم: الرأس (إن كان نصاً) والمتن والتذييل، سطراً لكل منها، والمتغيرات {{1}}… كما هي. تملؤه مزامنة القوالب من Meta." },
  { name: "x_buttons_text", ttype: "text", field_description: "تسميات الأزرار", help: "تسمية كل زر في سطر. تملؤه مزامنة القوالب من Meta." },
];
const MESSAGE_FIELDS = [
  { name: "x_echo_status", ttype: "selection", field_description: "صدى المناقشة", selection: "[('posted', 'في المحادثة'), ('pending', 'بانتظار المحادثة'), ('failed', 'فشل الصدى'), ('none', 'بلا محادثة')]", help: "هل ظهرت الرسالة في محادثة الرقم «واتساب · الاسم · +الرقم». «بانتظار المحادثة» يُعاد كل 5 دقائق ثلاث مرات، ثم «فشل الصدى»." },
  { name: "x_echo_message_id", ttype: "integer", field_description: "رسالة المناقشة", help: "معرّف رسالة المحادثة التي تعرض هذا الإرسال (وسطر حالته إن كان محفوظاً)." },
  { name: "x_backfilled", ttype: "boolean", field_description: "مستكمل", help: "سجل كُتب بأثر رجعي من سجل الإرسال (D1)، ووقته وقت الإرسال الفعلي." },
];
const SETTINGS_GROUP = 4; // base.group_system (ir.model.data 4934)
const WA_LIST = 2775, WA_FORM = 2778;
const VIEW_NAMES = { list: "x_wa_message.tree.s36_echo", form: "x_wa_message.form.s36_echo" };
const LIST_ARCH = `<data>
  <xpath expr="//field[@name='create_date']" position="after">
    <field name="x_processed_at" string="وقت الإرسال" optional="show"/>
  </xpath>
  <xpath expr="//field[@name='x_status']" position="after">
    <field name="x_echo_status" string="المحادثة" widget="badge" optional="show" decoration-success="x_echo_status == 'posted'" decoration-warning="x_echo_status == 'pending'" decoration-danger="x_echo_status == 'failed'"/>
    <field name="x_backfilled" string="مستكمل" optional="show"/>
  </xpath>
</data>`;
const FORM_ARCH = `<data>
  <xpath expr="//field[@name='x_processed_at']" position="after">
    <field name="x_echo_status" widget="badge" readonly="1"/>
    <field name="x_echo_message_id" readonly="1"/>
    <field name="x_backfilled" readonly="1"/>
  </xpath>
</data>`;

type Snap = {
  at: string;
  before: { templateFields: string[]; messageFields: string[]; action: number | null; views: Record<string, number | null> };
  created: { fields: number[]; action: number | null; views: number[] };
};
const snap: Snap = existsSync(RB) ? JSON.parse(readFileSync(RB, "utf8")) : null as unknown as Snap;
const save = (s: Snap) => writeFileSync(RB, JSON.stringify(s, null, 2) + "\n");

async function modelId(model: string): Promise<number> {
  const [m] = await call("ir.model", "search_read", { domain: [["model", "=", model]], fields: ["id"], limit: 1 });
  if (!m) throw new Error(`no model ${model}`);
  return m.id;
}
async function fieldRows(model: string, names: string[]): Promise<any[]> {
  return call("ir.model.fields", "search_read", {
    domain: [["model", "=", model], ["name", "in", names]],
    fields: ["id", "name", "ttype", "field_description", "selection_ids"],
  });
}
async function actionRow(): Promise<any | null> {
  const [a] = await call("ir.actions.server", "search_read", {
    domain: [["name", "=", HELD_LINE_ACTION_NAME]], fields: ["id", "name", "state", "code", "model_id", "group_ids"], limit: 1,
  });
  return a ?? null;
}
async function viewRow(name: string): Promise<any | null> {
  const [v] = await call("ir.ui.view", "search_read", {
    domain: [["name", "=", name]], fields: ["id", "name", "active", "inherit_id", "arch_db"], context: { active_test: false }, limit: 1,
  });
  return v ?? null;
}

// ---------------------------------------------------------------- rollback
if (ROLLBACK) {
  if (!snap) throw new Error("no rollback file");
  log(`rollback${DROP ? " --drop" : ""} ${APPLY ? "APPLY" : "(dry)"} — ${RB}`);
  const views = snap.created.views;
  log(`  views ${views.join(",") || "-"} → ${DROP ? "delete" : "inactive"}`);
  log(`  action ${snap.created.action ?? "-"} → ${DROP ? "delete" : "no-op code"}`);
  if (DROP) log(`  fields ${snap.created.fields.join(",") || "-"} → delete (their values go with them)`);
  if (APPLY) {
    if (views.length) {
      if (DROP) await call("ir.ui.view", "unlink", { ids: views });
      else await call("ir.ui.view", "write", { ids: views, vals: { active: false } });
    }
    if (snap.created.action) {
      if (DROP) await call("ir.actions.server", "unlink", { ids: [snap.created.action] });
      else await call("ir.actions.server", "write", { ids: [snap.created.action], vals: { code: "# UTAK § 36 — rolled back: no-op\naction = False\n" } });
    }
    if (DROP && snap.created.fields.length) await call("ir.model.fields", "unlink", { ids: snap.created.fields });
    log("  done");
  }
  process.exit(0);
}

// ---------------------------------------------------------------- verify
async function verify(): Promise<boolean> {
  const checks: Array<[string, boolean, string?]> = [];
  const check = (n: string, ok: boolean, d = "") => checks.push([n, ok, d]);
  const tf = await call("x_whatsapp_template", "fields_get", { attributes: ["type", "string"] });
  for (const f of TEMPLATE_FIELDS) check(`x_whatsapp_template.${f.name} ${f.ttype}`, tf[f.name]?.type === f.ttype);
  const mf = await call("x_wa_message", "fields_get", { attributes: ["type", "string", "selection"] });
  for (const f of MESSAGE_FIELDS) check(`x_wa_message.${f.name} ${f.ttype}`, mf[f.name]?.type === f.ttype);
  const sel = (mf.x_echo_status?.selection ?? []).map((s: string[]) => s[0]).join(",");
  check("x_echo_status values posted,pending,failed,none", sel === "posted,pending,failed,none", sel);
  const a = await actionRow();
  check("server action exists (code, x_wa_message)", !!a && a.state === "code" && a.model_id?.[0] === (await modelId("x_wa_message")), JSON.stringify(a?.model_id));
  check("server action code = heldLineActionCode()", !!a && a.code === heldLineActionCode());
  check("server action limited to Settings", !!a && (a.group_ids ?? []).includes(SETTINGS_GROUP), JSON.stringify(a?.group_ids));
  // python3: the stored functions against the TS ones
  if (a) {
    const cases = [
      ["sent", "21:40", ""], ["delivered", "06:03", ""], ["read", "", ""], ["expired", "", "البوابة: انتهت"],
      ["skipped", "", "البوابة: Meta رفض الغرض <x> & y"], ["failed", "", "Meta 131049: dropped"], ["held", "", ""], ["queued", "", ""],
    ];
    const bodies = [
      `<p style="border-right-style:solid"><strong>🤖 آلي</strong><br/>نص</p><p>${STATUS_MARKERS[0]}: خارج نافذة</p>`,
      `<p style="x"><strong>🤖 آلي</strong><br/>نص</p><p>✅ أُرسلت 21:40</p>`,
      `<p style="x"><strong>🤖 آلي</strong><br/>نص بلا سطر حالة</p>`,
      `<p>عادي</p>`,
    ];
    const prog = a.code.split("\nbot = ")[0] + `
import json, sys
cases = json.loads(sys.argv[1]); bodies = json.loads(sys.argv[2])
out = {"lines": [status_line(*c) for c in cases], "bodies": [[new_body(b, status_line(*c)) for c in cases] for b in bodies]}
print(json.dumps(out, ensure_ascii=False))`;
    const py = JSON.parse(execFileSync("python3", ["-c", prog, JSON.stringify(cases), JSON.stringify(bodies)], { encoding: "utf8" }));
    const ts = {
      lines: cases.map(([s, at, e]) => statusLineFor(s, at, e)),
      bodies: bodies.map((b) => cases.map(([s, at, e]) => replaceStatusLine(b, statusLineFor(s, at, e)))),
    };
    check("python3 status_line = statusLineFor (8 states)", JSON.stringify(py.lines) === JSON.stringify(ts.lines), JSON.stringify({ py: py.lines, ts: ts.lines }).slice(0, 600));
    check("python3 new_body = replaceStatusLine (4 bodies × 8 states)", JSON.stringify(py.bodies) === JSON.stringify(ts.bodies));
  }
  for (const [k, base] of [["list", WA_LIST], ["form", WA_FORM]] as const) {
    const v = await viewRow(VIEW_NAMES[k]);
    check(`view ${VIEW_NAMES[k]} active on ${base}`, !!v && v.active && v.inherit_id?.[0] === base);
  }
  const gv = await call("x_wa_message", "get_views", { views: [[false, "list"], [false, "form"]] });
  const listArch = String(gv?.views?.list?.arch ?? ""), formArch = String(gv?.views?.form?.arch ?? "");
  check("get_views list shows x_echo_status, x_backfilled and «وقت الإرسال» (x_processed_at)", listArch.includes('name="x_echo_status"') && listArch.includes('name="x_backfilled"') && listArch.includes('name="x_processed_at"'));
  check("get_views form shows x_echo_status, x_echo_message_id, x_backfilled", ["x_echo_status", "x_echo_message_id", "x_backfilled"].every((f) => formArch.includes(`name="${f}"`)));
  const autos = await call("base.automation", "search_read", { domain: [["id", "in", [7, 12]]], fields: ["id", "trigger", "filter_domain", "active"] });
  const a7 = autos.find((x: any) => x.id === 7), a12 = autos.find((x: any) => x.id === 12);
  check("automation 7 still only on x_status = queued", !!a7 && /x_status.*queued/.test(a7.filter_domain) && a7.active);
  check("automation 12 still on_create, author ≠ 42 (a bot edit or reply never sends)", !!a12 && a12.trigger === "on_create" && /author_id.*!=.*42/.test(a12.filter_domain) && a12.active);
  const bad = checks.filter((c) => !c[1]);
  for (const [n, ok, d] of checks) log(`  ${ok ? "✓" : "✗"} ${n}${!ok && d ? ` — ${d}` : ""}`);
  log(`verify: ${checks.length - bad.length}/${checks.length}`);
  writeFileSync(new URL("./artifacts/s36-20260925-odoo-verify.json", import.meta.url), JSON.stringify({ at: new Date().toISOString(), checks }, null, 2) + "\n");
  return bad.length === 0;
}

if (VERIFY && !APPLY) {
  process.exit((await verify()) ? 0 : 1);
}

// ---------------------------------------------------------------- plan / apply
const tfr = await fieldRows("x_whatsapp_template", TEMPLATE_FIELDS.map((f) => f.name));
const mfr = await fieldRows("x_wa_message", MESSAGE_FIELDS.map((f) => f.name));
const act = await actionRow();
const views = { list: await viewRow(VIEW_NAMES.list), form: await viewRow(VIEW_NAMES.form) };
log("plan:");
for (const f of TEMPLATE_FIELDS) log(`  x_whatsapp_template.${f.name} (${f.ttype}) ${tfr.some((r) => r.name === f.name) ? "= exists" : "+ create"}`);
for (const f of MESSAGE_FIELDS) log(`  x_wa_message.${f.name} (${f.ttype}) ${mfr.some((r) => r.name === f.name) ? "= exists" : "+ create"}`);
log(`  server action «${HELD_LINE_ACTION_NAME}» ${act ? `= #${act.id}${act.code === heldLineActionCode() ? "" : " (code differs → rewrite)"}` : "+ create"}`);
for (const k of ["list", "form"] as const) log(`  view ${VIEW_NAMES[k]} ${views[k] ? `= #${views[k].id}` : "+ create"}`);
log(`  code: ${heldLineActionCode().split("\n").length} lines`);
if (!APPLY) { log("(dry — add --apply)"); process.exit(0); }

const s: Snap = snap ?? {
  at: new Date().toISOString(),
  before: {
    templateFields: tfr.map((r) => r.name), messageFields: mfr.map((r) => r.name), action: act?.id ?? null,
    views: { list: views.list?.id ?? null, form: views.form?.id ?? null },
  },
  created: { fields: [], action: null, views: [] },
};
save(s);
log(`snapshot → ${RB}`);

const tm = await modelId("x_whatsapp_template"), wm = await modelId("x_wa_message");
for (const [mid, defs, have] of [[tm, TEMPLATE_FIELDS, tfr], [wm, MESSAGE_FIELDS, mfr]] as const) {
  for (const d of defs) {
    if ((have as any[]).some((r) => r.name === d.name)) continue;
    const [id] = await call("ir.model.fields", "create", { vals_list: [{ model_id: mid, ...d }] });
    s.created.fields.push(id); save(s);
    log(`  + field ${d.name} #${id}`);
  }
}
if (!act) {
  const [id] = await call("ir.actions.server", "create", { vals_list: [{
    name: HELD_LINE_ACTION_NAME, model_id: wm, state: "code", code: heldLineActionCode(), group_ids: [[6, 0, [SETTINGS_GROUP]]],
  }] });
  s.created.action = id; save(s);
  log(`  + server action #${id}`);
} else if (act.code !== heldLineActionCode()) {
  await call("ir.actions.server", "write", { ids: [act.id], vals: { code: heldLineActionCode() } });
  log(`  ~ server action #${act.id} code rewritten`);
}
for (const [k, base, arch] of [["list", WA_LIST, LIST_ARCH], ["form", WA_FORM, FORM_ARCH]] as const) {
  if (views[k]) {
    // this script's own view: brought to the current arch (the list gained «وقت الإرسال»)
    if (s.created.views.includes(views[k].id) && String(views[k].arch_db).replace(/\s+/g, " ").trim() !== arch.replace(/\s+/g, " ").trim()) {
      await call("ir.ui.view", "write", { ids: [views[k].id], vals: { arch_db: arch } });
      log(`  ~ view ${VIEW_NAMES[k]} #${views[k].id} arch updated`);
    }
    continue;
  }
  const [id] = await call("ir.ui.view", "create", { vals_list: [{
    name: VIEW_NAMES[k], model: "x_wa_message", type: k, inherit_id: base, mode: "extension", arch_db: arch, priority: 30,
  }] });
  s.created.views.push(id); save(s);
  log(`  + view ${VIEW_NAMES[k]} #${id}`);
}
log("applied");
process.exit((await verify()) ? 0 : 1);
