// Every outbound WhatsApp message on record — 2026-09-25 (STATUS § 36).
//
// A message the gateway (src/wa-gateway.ts) hands to Meta — or holds — gets,
// from here:
//   1. an x_wa_message row, written before the send returns, on the number's
//      partner (Baraa's number too: his channel is «واتساب · … · +966…4962»).
//      Its text (x_body) is the message exactly as the recipient reads it: a
//      template is rendered from its approved text in Odoo (x_body_text /
//      x_buttons_text, filled by the template sync) with the variables filled
//      in and one «🔘 label» line per button. The template's name stays in
//      technical fields (x_template_id, x_params, x_debug_payload) and never
//      reaches Discuss. A template whose text is not synced shows its filled
//      variables under «⚠️ نص القالب غير متزامن» — never the name alone.
//   2. a line in the number's Discuss channel, in § 28's style (the «🤖 آلي»
//      box). A held message shows its full text with a status line «⏳ محفوظة…»
//      under it; when it goes, expires, is dropped or refused, that same line
//      changes (server action «UTAK — سطر حالة رسالة واتساب», run as the row:
//      it edits only a bot line of a WhatsApp channel that this row points to,
//      and only its last paragraph when that is a status line). When Odoo does
//      not edit it, a short reply under the message says the same.
// The Discuss line never holds up the send or the row. A line that could not
// be posted leaves the row x_echo_status «pending»; the */5 tick retries it
// three times, then marks the row «failed». A row Odoo refused to create is
// kept in KV and retried the same way (the D1 log keeps every send anyway).

import type { Env } from "./config";
import { waDigits } from "./wa-window";
import { arabicDate, maskPhone } from "./wa-params";
import { riyadhDateKey, riyadhMinutes } from "./hours";

// ------------------------------------------------------------------ texts

/** The first characters of every status line (the server action finds the line by them). */
export const STATUS_MARKERS = ["⏳ محفوظة", "✅ أُرسلت", "⌛ انتهت", "⏭️ لم تُرسل", "⚠️ لم تصل"] as const;
export const UNSYNCED_LINE = "⚠️ نص القالب غير متزامن";
export const BACKFILL_TAG = "مستكمل";
export const HELD_LINE_ACTION_NAME = "UTAK — سطر حالة رسالة واتساب";

/** «⏳ محفوظة…» under a held message: what waits, and until when. */
export function heldLine(until: string): string {
  return `⏳ محفوظة: خارج نافذة 24 ساعة ولا قالب معتمد لها. تُرسل تلقائياً عند أول رسالة منه، وتنتهي صلاحيتها ${until}.`;
}

/** Riyadh «HH:MM» of an Odoo UTC datetime ("YYYY-MM-DD HH:MM:SS"), or "". */
export function riyadhHHMM(odooUtc: string | false | null | undefined): string {
  const ms = Date.parse(String(odooUtc || "").replace(" ", "T") + "Z");
  if (!Number.isFinite(ms)) return "";
  const m = riyadhMinutes(new Date(ms));
  return `${String(Math.floor(m / 60)).padStart(2, "0")}:${String(m % 60).padStart(2, "0")}`;
}

/**
 * The status line for a row's x_status — the same function as the server
 * action's Python (heldLineActionCode), checked against it by the setup
 * script. "" = no line for that status.
 */
export function statusLineFor(status: string, at: string, metaError: string): string {
  const err = String(metaError || "").replace("البوابة: ", "").slice(0, 200);
  if (status === "sent" || status === "delivered" || status === "read") return "✅ أُرسلت" + (at ? " " + at : "");
  if (status === "expired") return "⌛ انتهت صلاحيتها ولم تُرسل: لم يراسل الرقم قبلها.";
  if (status === "skipped") return "⏭️ لم تُرسل: " + err;
  if (status === "failed") return "⚠️ لم تصل: " + err;
  if (status === "held") return "⏳ محفوظة من جديد: أغلق Meta النافذة، وتُرسل عند أول رسالة منه.";
  return "";
}

function escapeHtml(s: string): string {
  return String(s ?? "").replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;");
}

/**
 * A body whose last paragraph is a status line, with that line replaced — or
 * null when the last paragraph is not one (the message is left alone). The
 * server action does exactly this (heldLineActionCode).
 */
export function replaceStatusLine(body: string, line: string): string | null {
  const b = String(body ?? "");
  const i = b.lastIndexOf("<p>");
  if (i < 0 || !STATUS_MARKERS.some((m) => b.slice(i + 3).startsWith(m))) return null;
  return b.slice(0, i) + "<p>" + escapeHtml(line) + "</p>";
}

/**
 * The Python of the server action — generated from the functions above so the
 * two never drift (scripts/s36-20260925-odoo.mts writes it and --verify runs
 * its functions in python3 against statusLineFor / replaceStatusLine).
 */
export function heldLineActionCode(): string {
  const py = (s: string) => JSON.stringify(s);
  return `# UTAK § 36 — the status line of a WhatsApp message in its Discuss channel.
# Generated by src/wa-record.ts heldLineActionCode(); do not edit here.
# Run as the x_wa_message row(s): edits only the Discuss message the row
# points to (x_echo_message_id), only when it is a line of «UTAK بوت» in a
# WhatsApp channel, and only its last paragraph when that is a status line.
MARKERS = (${STATUS_MARKERS.map(py).join(", ")})

def status_line(st, at, err):
    err = (err or '').replace(${py("البوابة: ")}, '', 1)[:200]
    if st in ('sent', 'delivered', 'read'):
        return ${py("✅ أُرسلت")} + ((' ' + at) if at else '')
    if st == 'expired':
        return ${py(statusLineFor("expired", "", ""))}
    if st == 'skipped':
        return ${py("⏭️ لم تُرسل: ")} + err
    if st == 'failed':
        return ${py("⚠️ لم تصل: ")} + err
    if st == 'held':
        return ${py(statusLineFor("held", "", ""))}
    return ''

def esc(s):
    return s.replace('&', '&amp;').replace('<', '&lt;').replace('>', '&gt;')

def new_body(body, line):
    i = body.rfind('<p>')
    if i < 0 or not body[i + 3:].startswith(MARKERS):
        return None
    return body[:i] + '<p>' + esc(line) + '</p>'

bot = env['res.partner'].sudo().search([('name', '=', ${py("UTAK بوت")})], limit=1)
updated = 0
for rec in records:
    mid = rec.x_echo_message_id
    if not mid or not bot:
        continue
    msg = env['mail.message'].sudo().browse(mid).exists()
    if not msg or msg.model != 'discuss.channel' or msg.author_id != bot or msg.message_type != 'comment':
        continue
    if not env['discuss.channel'].sudo().browse(msg.res_id).x_wa_partner_id:
        continue
    at = ''
    if rec.x_processed_at:
        at = (rec.x_processed_at + datetime.timedelta(hours=3)).strftime('%H:%M')
    line = status_line(rec.x_status or '', at, rec.x_meta_error or '')
    if not line:
        continue
    body = new_body(str(msg.body or ''), line)
    if body is None:
        continue
    if body != str(msg.body or ''):
        msg.write({'body': body})
    updated += 1
action = {'type': 'ir.actions.act_window_close', 'infos': {'utak_updated': updated}}
`;
}

// ------------------------------------------------------------------ what the recipient reads

export interface TemplateText {
  id: number;
  name: string;
  /** Header (text), body and footer as Meta approved them, {{n}} unfilled. */
  bodyText: string;
  /** Button labels, one per line. */
  buttonsText: string;
}

const TEXT_TTL_MS = 10 * 60 * 1000;
const textCache = new Map<string, { t: TemplateText | null; at: number }>();
/** Test hook. */
export function clearTemplateTextCache(): void { textCache.clear(); }

/** The approved text of template `name` from its x_whatsapp_template row (10-minute cache). */
export async function templateText(env: Env, name: string, language = "ar"): Promise<TemplateText | null> {
  const key = `${name}::${language}`;
  const hit = textCache.get(key);
  if (hit && Date.now() - hit.at < TEXT_TTL_MS) return hit.t;
  try {
    const { call } = await import("./odoo");
    const rows = await call<Array<{ id: number; x_meta_template_id: string; x_language: string | false; x_body_text: string | false; x_buttons_text: string | false }>>(
      env, "x_whatsapp_template", "search_read", {
        domain: [["x_meta_template_id", "=", name]],
        fields: ["id", "x_meta_template_id", "x_language", "x_body_text", "x_buttons_text"],
        limit: 5,
      });
    const row = rows.find((r) => String(r.x_language || "").toLowerCase() === language.toLowerCase()) ?? rows[0];
    const t = row ? { id: row.id, name, bodyText: String(row.x_body_text || ""), buttonsText: String(row.x_buttons_text || "") } : null;
    if (t) textCache.set(key, { t, at: Date.now() });
    return t;
  } catch (e) {
    console.warn(`[record] template text ${name} unreadable`, (e as Error)?.message);
    return null;
  }
}

type TemplateBody = {
  template?: {
    name?: string;
    language?: { code?: string };
    components?: Array<{ type?: string; parameters?: Array<{ type?: string; text?: string; document?: { filename?: string }; image?: unknown; video?: unknown }> }>;
  };
};

/** {{1}}, {{2}}, … of a template body as sent. */
export function templateParams(body: Record<string, unknown>): string[] {
  const comps = (body as TemplateBody).template?.components ?? [];
  return comps.filter((c) => c?.type === "body").flatMap((c) => c.parameters ?? []).map((p) => String(p?.text ?? ""));
}

function headerLine(body: Record<string, unknown>): string {
  const comps = (body as TemplateBody).template?.components ?? [];
  const p = comps.find((c) => c?.type === "header")?.parameters?.[0];
  if (!p) return "";
  if (p.type === "document") return `📎 ${p.document?.filename ?? "مستند"}`;
  if (p.type === "image") return "🖼️ صورة";
  if (p.type === "video") return "🎬 فيديو";
  return "";
}

/**
 * A template message as its recipient reads it: the approved text with the
 * variables filled in, a media header as one line, the buttons as «🔘 label».
 * Without the approved text: the filled variables under UNSYNCED_LINE.
 */
export function renderTemplateMessage(t: TemplateText | null, body: Record<string, unknown>): { text: string; synced: boolean } {
  const params = templateParams(body);
  const head = headerLine(body);
  if (!t || !t.bodyText.trim()) {
    const lines = [head, UNSYNCED_LINE, ...params.filter((p) => p !== "").map((p) => `• ${p}`)].filter(Boolean);
    return { text: lines.join("\n"), synced: false };
  }
  const filled = t.bodyText.replace(/\{\{(\d+)\}\}/g, (m, n) => params[Number(n) - 1] ?? m);
  const buttons = t.buttonsText.split("\n").map((l) => l.trim()).filter(Boolean).map((l) => `🔘 ${l}`);
  return { text: [head, filled.trim(), ...buttons].filter(Boolean).join("\n"), synced: true };
}

/** A session (non-template) message as its recipient reads it. */
export function sessionText(body: Record<string, unknown>): string {
  const b = body as {
    type?: string;
    text?: { body?: string };
    location?: { latitude?: number; longitude?: number; name?: string; address?: string };
    interactive?: { body?: { text?: string }; action?: { buttons?: Array<{ reply?: { title?: string } }> } };
    document?: { filename?: string };
    template?: unknown;
  };
  if (b.type === "text") return String(b.text?.body ?? "");
  if (b.type === "location") {
    const label = b.location?.name ?? b.location?.address ?? "";
    return `📍 موقع${label ? " · " + label : ""} — https://maps.google.com/?q=${b.location?.latitude},${b.location?.longitude}`;
  }
  if (b.type === "interactive") {
    const text = b.interactive?.body?.text ?? "";
    const btns = (b.interactive?.action?.buttons ?? []).map((btn) => btn?.reply?.title ?? "").filter(Boolean).map((t) => `🔘 ${t}`);
    return [text, ...btns].filter(Boolean).join("\n");
  }
  if (b.type === "document") return `📎 ${b.document?.filename ?? "مستند"}`;
  if (b.type === "template") return renderTemplateMessage(null, body).text;
  return `[${b.type ?? "unknown"}]`;
}

export interface Shown {
  text: string;
  kind: "text" | "template" | "document";
  templateId?: number;
  templateName?: string;
  params?: string[];
  synced: boolean;
}

/** What the recipient reads, for any body the gateway sends (templates read their text from Odoo). */
export async function outboundText(env: Env, body: Record<string, unknown>): Promise<Shown> {
  const type = String((body as { type?: string }).type ?? "");
  if (type !== "template") {
    return { text: sessionText(body), kind: type === "document" ? "document" : "text", synced: true };
  }
  const tb = body as TemplateBody;
  const name = String(tb.template?.name ?? "");
  const t = name ? await templateText(env, name, tb.template?.language?.code || "ar") : null;
  const r = renderTemplateMessage(t, body);
  return { text: r.text, kind: "template", templateId: t?.id, templateName: name || undefined, params: templateParams(body), synced: r.synced };
}

// ------------------------------------------------------------------ the Discuss line

export interface EchoOpts {
  template?: boolean;
  manual?: boolean;
  backfilled?: boolean;
  /** A status paragraph under the box (held, and a held message's later fate). */
  status?: string;
}

/** The § 28 box (theme-inherited, «🤖 آلي» / «📤 يدوي»), with an optional status line under it. */
export function echoHtml(text: string, o: EchoOpts = {}): string {
  const tags = [o.manual ? "📤 يدوي" : "🤖 آلي", o.template ? "قالب" : "", o.backfilled ? BACKFILL_TAG : ""].filter(Boolean).join(" · ");
  const body = escapeHtml(text).replace(/\n/g, "<br/>");
  // AUTO_STYLE, as in src/wa-inbox.ts (kept literal here: no static import cycle)
  const box = `<p style="border-right-style:solid; border-right-width:3px; padding-right:8px; margin:0"><strong>${tags}</strong><br/>${body}</p>`;
  return o.status ? `${box}<p>${escapeHtml(o.status)}</p>` : box;
}

/** The partner whose channel shows this number — Baraa's included (§ 36). */
export async function partnerForNumber(env: Env, to: string): Promise<{ id: number; name: string } | null> {
  const digits = waDigits(to);
  if (!digits) return null;
  try {
    const { inboxPartnerForNumber } = await import("./wa-inbox");
    const byChannel = await inboxPartnerForNumber(env, digits);
    if (byChannel) return byChannel;
    const { call } = await import("./odoo");
    const rows = await call<Array<{ id: number; name: string }>>(env, "res.partner", "search_read", {
      domain: ["|", ["x_whatsapp_number", "ilike", digits], ["phone", "ilike", digits]],
      fields: ["id", "name"],
      limit: 1,
    });
    return rows[0] ?? null;
  } catch {
    return null;
  }
}

/** The id message_post answered with: a number, [id], or {id} (JSON-2 serialises the record). */
function msgId(v: unknown): number | null {
  const n = Array.isArray(v) ? v[0] : v && typeof v === "object" ? (v as { id?: unknown }).id : v;
  return typeof n === "number" && n > 0 ? n : null;
}

/** Post `html` in the partner's channel as «UTAK بوت». Returns the message id, or null. */
async function postEcho(
  env: Env,
  partner: { id: number; name: string },
  number: string,
  html: string,
  extra: Record<string, unknown> = {},
): Promise<number | null> {
  const { ensureInboxChannel, getBotPartnerId, stripFixedColors } = await import("./wa-inbox");
  const channelId = await ensureInboxChannel(env, partner.id, partner.name, { number });
  if (!channelId) throw new Error("no channel");
  const bot = await getBotPartnerId(env);
  if (!bot) throw new Error("UTAK بوت partner missing");
  const { call } = await import("./odoo");
  const res = await call<unknown>(env, "discuss.channel", "message_post", {
    ids: [channelId],
    body: stripFixedColors(html),
    body_is_html: true,
    message_type: "comment",
    author_id: bot,
    subtype_xmlid: "mail.mt_comment",
    ...extra,
  });
  return msgId(res) ?? 0;
}

const ACTION_KEY = "wa_rec:v1:line_action_id";
async function lineActionId(env: Env): Promise<number | null> {
  try {
    const cached = await env.MSG_DEDUP.get(ACTION_KEY);
    if (cached) return Number(cached) || null;
  } catch { /* ignore */ }
  try {
    const { call } = await import("./odoo");
    const rows = await call<Array<{ id: number }>>(env, "ir.actions.server", "search_read", {
      domain: [["name", "=", HELD_LINE_ACTION_NAME]], fields: ["id"], limit: 1,
    });
    const id = rows[0]?.id ?? null;
    if (id) { try { await env.MSG_DEDUP.put(ACTION_KEY, String(id), { expirationTtl: 3600 }); } catch { /* ignore */ } }
    return id;
  } catch {
    return null;
  }
}

/** Run the server action on row `rowId`: true when it edited the line. */
async function editStatusLine(env: Env, rowId: number): Promise<boolean> {
  const actionId = await lineActionId(env);
  if (!actionId) return false;
  try {
    const { call } = await import("./odoo");
    const res = await call<{ infos?: { utak_updated?: number } } | null>(env, "ir.actions.server", "run", {
      ids: [actionId],
      context: { active_model: "x_wa_message", active_id: rowId, active_ids: [rowId] },
    });
    return Number(res?.infos?.utak_updated ?? 0) > 0;
  } catch (e) {
    console.warn(`[record] status line edit row=${rowId} refused`, (e as Error)?.message);
    return false;
  }
}

// ------------------------------------------------------------------ the row

export const ROW_FIELDS = [
  "id", "x_partner_id", "x_body", "x_kind", "x_status", "x_source", "x_manual", "x_processed_at", "x_meta_error",
  "x_debug_payload", "x_echo_status", "x_echo_message_id", "x_backfilled", "x_meta_message_id",
];

export interface RowView {
  id: number;
  x_partner_id: [number, string] | false;
  x_body: string | false;
  x_kind: string | false;
  x_status: string | false;
  x_source: string | false;
  x_manual?: boolean;
  x_processed_at: string | false;
  x_meta_error: string | false;
  x_debug_payload: string | false;
  x_echo_status: string | false;
  x_echo_message_id: number | false;
  x_backfilled?: boolean;
}

const SENT_LIKE = new Set(["sent", "delivered", "read"]);
const nowOdoo = (ms: number = Date.now()) => new Date(ms).toISOString().replace("T", " ").slice(0, 19);

function heldUntilOf(row: RowView): string {
  try {
    const p = JSON.parse(String(row.x_debug_payload || "{}"));
    const ms = Date.parse(p.expiresAt);
    if (Number.isFinite(ms)) return riyadhLabel(ms);
  } catch { /* ignore */ }
  return "نهاية اليوم";
}

export function riyadhLabel(ms: number): string {
  const d = new Date(ms);
  const m = riyadhMinutes(d);
  return `${arabicDate(riyadhDateKey(d))}، ${String(Math.floor(m / 60)).padStart(2, "0")}:${String(m % 60).padStart(2, "0")}`;
}

/**
 * The row's Discuss line, whatever its state: a held line posted when there is
 * none, a status line edited (or a reply) when the message changed fate, the
 * full echo for a message that went. Throws when the line could not be posted.
 * Returns the message id it wrote on the row, or null when nothing applies.
 */
export async function echoForRow(env: Env, row: RowView, numberHint?: string): Promise<number | null> {
  const partner = row.x_partner_id ? { id: row.x_partner_id[0], name: row.x_partner_id[1] } : null;
  if (!partner) {
    await writeRow(env, row.id, { x_echo_status: "none" });
    return null;
  }
  const status = String(row.x_status || "");
  const text = String(row.x_body || "");
  const at = riyadhHHMM(row.x_processed_at);
  const opts: EchoOpts = { template: row.x_kind === "template", manual: row.x_source === "manual" || row.x_manual === true, backfilled: row.x_backfilled === true };
  const number = numberHint ?? "";
  if (row.x_echo_message_id) {
    // a held line exists: its status changes, or a reply says so
    const line = statusLineFor(status, at, String(row.x_meta_error || ""));
    if (line && !(await editStatusLine(env, row.id))) {
      const { ensureInboxChannel } = await import("./wa-inbox");
      if (!(await ensureInboxChannel(env, partner.id, partner.name, { number }))) throw new Error("no channel");
      await postEcho(env, partner, number, `<p>${escapeHtml(line)}</p>`, { parent_id: row.x_echo_message_id });
    }
    await writeRow(env, row.id, { x_echo_status: "posted" });
    return row.x_echo_message_id;
  }
  if (!text) {
    await writeRow(env, row.id, { x_echo_status: "none" });
    return null;
  }
  let html: string;
  if (status === "held") html = echoHtml(text, { ...opts, status: heldLine(heldUntilOf(row)) });
  else if (SENT_LIKE.has(status)) html = echoHtml(text, opts);
  else html = echoHtml(text, { ...opts, status: statusLineFor(status, at, String(row.x_meta_error || "")) });
  const id = await postEcho(env, partner, number, html);
  await writeRow(env, row.id, { x_echo_status: "posted", ...(id ? { x_echo_message_id: id } : {}) });
  return id;
}

async function writeRow(env: Env, id: number, vals: Record<string, unknown>): Promise<void> {
  const { call } = await import("./odoo");
  await call(env, "x_wa_message", "write", { ids: [id], vals });
}

async function readRow(env: Env, id: number): Promise<RowView | null> {
  const { call } = await import("./odoo");
  const rows = await call<RowView[]>(env, "x_wa_message", "read", { ids: [id], fields: ROW_FIELDS });
  return rows[0] ?? null;
}

/** The row's line now (awaited, or in ctx.waitUntil). A failure leaves «pending» for the every-5-minutes retry. */
export async function echoRowSoon(env: Env, rowId: number | undefined, number: string, ctx?: ExecutionContext): Promise<void> {
  if (!rowId) return;
  const task = (async () => {
    try {
      const row = await readRow(env, rowId);
      if (row) await echoForRow(env, row, number);
    } catch (e) {
      console.warn(`[record] Discuss line row=${rowId} to=${maskPhone(number)} failed — retried by the */5 tick`, (e as Error)?.message);
    }
  })();
  if (ctx) ctx.waitUntil(task);
  else await task;
}

// ------------------------------------------------------------------ a send, on record

export interface SentRecord {
  to: string;
  purpose: string;
  /** The body that went to Meta. */
  body: Record<string, unknown>;
  wamid?: string;
  sentAt?: number;
  /** An existing row this send settles (a held message, an Odoo manual send). */
  rowId?: number;
  manual?: boolean;
  /** A Discuss reply is already its own line (inbox_reply): no echo. */
  noEcho?: boolean;
  ctx?: ExecutionContext;
}

/** Create an x_wa_message row — or find the one that already carries this wamid (one row per wamid). */
async function createRow(env: Env, vals: Record<string, unknown>): Promise<{ id: number; existed: boolean }> {
  const { call } = await import("./odoo");
  const wamid = typeof vals.x_meta_message_id === "string" ? vals.x_meta_message_id : "";
  if (wamid) {
    const hit = await call<Array<{ id: number }>>(env, "x_wa_message", "search_read", {
      domain: [["x_meta_message_id", "=", wamid]], fields: ["id"], limit: 1,
    });
    if (hit[0]) return { id: hit[0].id, existed: true };
  }
  const ids = await call<number[]>(env, "x_wa_message", "create", { vals_list: [vals] });
  const id = Array.isArray(ids) ? ids[0] : 0;
  if (!id) throw new Error("x_wa_message create returned no id");
  return { id, existed: false };
}

/** The row of a send (throws when Odoo refuses it). Returns its id and whether a line is due. */
async function writeSentRow(env: Env, rec: SentRecord): Promise<{ rowId: number; echo: boolean }> {
  const to = waDigits(rec.to);
  const sentAt = rec.sentAt ?? Date.now();
  const shown = await outboundText(env, rec.body);
  const partner = await partnerForNumber(env, to);
  const echo = !rec.noEcho && !!partner;
  const tech = {
    purpose: rec.purpose,
    ...(shown.templateName ? { template: shown.templateName } : {}),
    ...(shown.kind === "template" && !shown.synced ? { unsynced: true } : {}),
  };
  const vals: Record<string, unknown> = {
    x_status: "sent",
    x_meta_message_id: rec.wamid || false,
    x_processed_at: nowOdoo(sentAt),
    x_echo_status: echo ? "pending" : "none",
    ...(shown.templateId ? { x_template_id: shown.templateId } : {}),
    ...(shown.kind === "template" ? { x_params: JSON.stringify(shown.params ?? []) } : {}),
    ...(partner ? { x_partner_id: partner.id } : {}),
  };
  const { call } = await import("./odoo");
  // § 37 أ — Meta's «delivered» / «read» can arrive before this row carries the
  // wamid (the D1 status log kept it): the row starts at that status, not «sent».
  if (rec.wamid) {
    const { highestLoggedStatus } = await import("./wa-status");
    const hi = await highestLoggedStatus(env, rec.wamid);
    if (hi === "delivered" || hi === "read") vals.x_status = hi;
  }
  if (rec.rowId) {
    if (shown.kind === "template") vals.x_body = shown.text.slice(0, 2000);
    vals.x_source = rec.manual ? "manual" : "auto";
    await call(env, "x_wa_message", "write", { ids: [rec.rowId], vals });
    return { rowId: rec.rowId, echo };
  }
  const r = await createRow(env, {
    ...vals,
    x_direction: "out",
    x_kind: shown.kind,
    x_body: shown.text.slice(0, 2000),
    x_source: rec.manual ? "manual" : "auto",
    x_debug_payload: JSON.stringify(tech).slice(0, 4000),
  });
  // A row that already carried this wamid was written (and shown) by its own path.
  return { rowId: r.id, echo: echo && !r.existed };
}

/**
 * A message Meta accepted: its row (awaited — no message leaves without one),
 * then its Discuss line (in ctx.waitUntil when there is a ctx). A row Odoo
 * refuses is kept in KV for the every-5-minutes retry. Returns the row id.
 */
export async function recordSent(env: Env, rec: SentRecord): Promise<number | undefined> {
  let r: { rowId: number; echo: boolean };
  try {
    r = await writeSentRow(env, rec);
  } catch (e) {
    console.error(`[record] x_wa_message row for purpose=${rec.purpose} to=${maskPhone(rec.to)} failed — kept for the */5 retry`, (e as Error)?.message);
    await keepOrphan(env, { ...rec, sentAt: rec.sentAt ?? Date.now(), ctx: undefined });
    return undefined;
  }
  if (r.echo) await echoRowSoon(env, r.rowId, waDigits(rec.to), rec.ctx);
  return r.rowId;
}

/**
 * A held / expired / skipped / failed / re-held row changed state: its line
 * follows (the held line edited, or a line posted when there is none).
 */
export async function recordStateChange(env: Env, rowId: number | undefined, to: string, ctx?: ExecutionContext): Promise<void> {
  if (!rowId) return;
  try {
    const { call } = await import("./odoo");
    await call(env, "x_wa_message", "write", { ids: [rowId], vals: { x_echo_status: "pending" } });
  } catch (e) {
    console.warn(`[record] row=${rowId} pending mark failed`, (e as Error)?.message);
  }
  await echoRowSoon(env, rowId, waDigits(to), ctx);
}

// ------------------------------------------------------------------ retries (the */5 tick)

export const MAX_ECHO_RETRIES = 3;
export function echoTryKey(rowId: number): string {
  return `wa_echo_try:v1:${rowId}`;
}
const ORPHANS_KEY = "wa_rec:v1:orphans";
interface Orphan { rec: SentRecord; tries: number }

async function keepOrphan(env: Env, rec: SentRecord): Promise<void> {
  try {
    const raw = await env.MSG_DEDUP.get(ORPHANS_KEY);
    const list = (raw ? JSON.parse(raw) : []) as Orphan[];
    list.push({ rec, tries: 0 });
    await env.MSG_DEDUP.put(ORPHANS_KEY, JSON.stringify(list.slice(-200)), { expirationTtl: 3 * 24 * 3600 });
  } catch (e) {
    console.error("[record] orphan not kept (the D1 log still has the send)", (e as Error)?.message);
  }
}

/**
 * Every row whose Discuss line is still «pending» (older than two minutes, so
 * not one being posted right now): one more try each, three at most, then the
 * row is marked «failed». Rows Odoo refused to create are retried the same way.
 */
export async function retryPendingRecords(env: Env, now: number = Date.now()): Promise<{ echoed: number; failed: number; waiting: number; orphans: number }> {
  const out = { echoed: 0, failed: 0, waiting: 0, orphans: 0 };
  // rows Odoo refused to create
  try {
    const raw = await env.MSG_DEDUP.get(ORPHANS_KEY);
    const list = (raw ? JSON.parse(raw) : []) as Orphan[];
    if (list.length) {
      const keep: Orphan[] = [];
      for (const o of list) {
        try {
          const r = await writeSentRow(env, o.rec);
          out.orphans++;
          if (r.echo) await echoRowSoon(env, r.rowId, waDigits(o.rec.to));
        } catch (e) {
          if (o.tries + 1 < MAX_ECHO_RETRIES) keep.push({ rec: o.rec, tries: o.tries + 1 });
          else console.error(`[record] row for purpose=${o.rec.purpose} to=${maskPhone(o.rec.to)} still refused after ${MAX_ECHO_RETRIES} retries — only the D1 log has it`, (e as Error)?.message);
        }
      }
      // a send recorded meanwhile may have added an orphan: keep it too
      const now2 = JSON.parse((await env.MSG_DEDUP.get(ORPHANS_KEY)) ?? "[]") as Orphan[];
      const added = now2.slice(list.length);
      await env.MSG_DEDUP.put(ORPHANS_KEY, JSON.stringify([...keep, ...added]), { expirationTtl: 3 * 24 * 3600 });
    }
  } catch (e) {
    console.warn("[record] orphan retry failed", (e as Error)?.message);
  }
  // rows whose line is pending
  let rows: RowView[] = [];
  try {
    const { call } = await import("./odoo");
    rows = await call<RowView[]>(env, "x_wa_message", "search_read", {
      domain: [["x_echo_status", "=", "pending"], ["write_date", "<=", nowOdoo(now - 2 * 60_000)], ["write_date", ">=", nowOdoo(now - 3 * 24 * 3600_000)]],
      fields: ROW_FIELDS,
      order: "id asc",
      limit: 30,
    });
  } catch (e) {
    console.warn("[record] pending rows unreadable", (e as Error)?.message);
    return out;
  }
  for (const row of rows) {
    const key = echoTryKey(row.id);
    let tries = 0;
    try { tries = Number((await env.MSG_DEDUP.get(key)) ?? "0") || 0; } catch { /* 0 */ }
    try {
      await echoForRow(env, row, await numberOfRow(env, row));
      out.echoed++;
    } catch (e) {
      tries++;
      if (tries >= MAX_ECHO_RETRIES) {
        try {
          await writeRow(env, row.id, { x_echo_status: "failed" });
          out.failed++;
          console.error(`[record] Discuss line row=${row.id} failed ${tries} retries — row marked «failed»`, (e as Error)?.message);
        } catch { out.waiting++; }
      } else {
        out.waiting++;
        try { await env.MSG_DEDUP.put(key, String(tries), { expirationTtl: 3 * 24 * 3600 }); } catch { /* ignore */ }
      }
    }
  }
  return out;
}

async function numberOfRow(env: Env, row: RowView): Promise<string> {
  if (!row.x_partner_id) return "";
  try {
    const { call } = await import("./odoo");
    const [p] = await call<Array<{ x_whatsapp_number: string | false; phone: string | false }>>(env, "res.partner", "read", {
      ids: [row.x_partner_id[0]], fields: ["x_whatsapp_number", "phone"], context: { active_test: false },
    });
    return waDigits(String(p?.x_whatsapp_number || p?.phone || ""));
  } catch {
    return "";
  }
}
